### ISSUE TITLE
统计比对到pUC19c质粒序列上bam文件的TotalDepth结果与samtools结果不一致

### ISSUE THREAD

**Issue by kinokokoko** [HuiyangYu/PanDepth#1]
我有一个对比到pUC19c质粒序列上的bam文件，用samtools depth计算出来total depth是76293504，pandepth计算出来的total depth只有61875584，相差较大，但是Length和CoveredSite计算结果与samtools depth保持一致

pandepth运行命令如下：
pandepth -i INPUT_BAM -o OUTPUT_PREFIX -r L09137.2.fasta

samtools depth运行命令如下：
samtools depth INPUT_BAM | awk '{sum+=$3} END {print sum}'

请教这是否是运行命令有问题导致的（猜测有可能是pandepth的-x参数默认值？）？如果我想要得到和samtools一致的结果，需要做怎样的处理？

期待您的回复，多谢！

**Comment by HuiyangYu** [comment]
您好，非常感谢您对PanDepth的使用，非常抱歉给您造成了使用上的困扰。

请问您使用的是哪个版本的samtools，如果您的samtools版本<1.10，麻烦您再使用 >=1.10版本的samtools再测试一下。

**Comment by kinokokoko** [comment]
> 您好，非常感谢您对PanDepth的使用，非常抱歉给您造成了使用上的困扰。
> 
> 请问您使用的是哪个版本的samtools，如果您的samtools版本<1.10，麻烦您再使用 >=1.10版本的samtools测试一下。

用的1.13版本samtools，我运行过比对到人类基因组上的bam，结果都是与samtools一致的，很奇怪只有pUC19c质粒序列的bam结果不一致

**Comment by hewm2008** [comment]
我大约知道是为什么了，我猜你的这个区域有一些位点的  的深度  高于65535 .    然后精度超了，你这种情况可以把   cpp代码中的   short unsigned int    改为   int     重新编译一下再次运行比较看看 。

**Comment by kinokokoko** [comment]
PanDepth/src/PanDepth.cpp: In function ‘int bamCov_help01(int, char**, In3str1v*)’:
PanDepth/src/PanDepth.cpp:191:14: error: ‘class In3str1v’ has no member named ‘WinSize’
    paraFA04->WinSize=atoi(argv[i]);
              ^~~~~~~
PanDepth/src/PanDepth.cpp:192:21: error: ‘class In3str1v’ has no member named ‘WinSize’
    if ( ( paraFA04->WinSize) <150)
                     ^~~~~~~
PanDepth/src/PanDepth.cpp:195:15: error: ‘class In3str1v’ has no member named ‘WinSize’
     paraFA04->WinSize=150;
               ^~~~~~~
PanDepth/src/PanDepth.cpp: In function ‘int main(int, char**)’:
PanDepth/src/PanDepth.cpp:1029:18: error: ‘class In3str1v’ has no member named ‘WinSize’
   if ((paraFA04->WinSize) < 150 )
                  ^~~~~~~
PanDepth/src/PanDepth.cpp:1037:29: error: ‘class In3str1v’ has no member named ‘WinSize’
    MeMBinWindows=(paraFA04->WinSize);
                             ^~~~~~~
Installation of PanDepth has failed.


请教下，运行sh install.sh编译时会出现以上报错（不修改cpp代码，git clone代码之后直接运行sh install.sh也会有这个报错）

**Comment by HuiyangYu** [comment]
是的，何老师说的对，这是PanDepth的bug。您pUC19c质粒的平均深度为28404，会有大部分区域在使用PanDepth统计时精度超出。对您造成的困扰非常抱歉，我会重新修改软件并上传。

**Comment by HuiyangYu** [comment]
PanDepth更新版（version 2.20）已经上传，修复了对深度大于65535位点统计存在的bug，您可以重新进行测试。如果还存在问题，您可上传您的bam/cram文件，或者通过邮件发送给我，以便更针对性的寻找原因。

**Comment by kinokokoko** [comment]
> PanDepth更新版（version 2.20）已经上传，修复了对深度大于65535位点统计存在的bug，您可以重新进行测试。如果还存在问题，您可上传您的bam/cram文件，或者通过邮件发送给我，以便更针对性的寻找原因。

感谢！刚刚测试了下已经和samtools结果完全一致了🙏
