### ISSUE TITLE
Coverage and depth could not be calculated after chromosomes exceeded 512MB

### ISSUE THREAD

**Issue by xuanzhaoli** [HuiyangYu/PanDepth#2]
When the chromosome exceeds 512MB, the coverage and depth cannot be calculated. samtools-1.3.1 can establish the index normally(.bai). What is the solution?

**Comment by hewm2008** [comment]
Please try one of the following:

 1  ：   Reindex it using samtools >1.15: xxx.bai xxx.csi
  2 ：  Delete xxx.bai and run it with the new algorithm, without using bam.bai, to obtain the result.

**Comment by HuiyangYu** [comment]
We have revised and uploaded version 2.21, which is compatible with CSI-format indexes. These indexes are typically used for alignment files with chromosomes larger than 512MB.
