### ISSUE TITLE
染色体间共享reads数目计算

### ISSUE THREAD

**Issue by xiekunwhy** [HuiyangYu/PanDepth#3]
你好，

不知道增加染色体/scaffold/contig间共享的reads数目计算是不是不太容易，就是允许多重比对的情况下，有部分reads会比对到多个contig/染色体/scaffold，想看看那些scaffold/contig间共享的reads比较多，好判断和去处冗余。

祝好！

**Comment by HuiyangYu** [comment]
感谢您对PanDepth的关注。非常抱歉，PanDepth的功能是快速统计比对文件在染色体/scaffold/contig上的覆盖率和覆盖深度。如果您想针对组装基因组的冗余去除，可以考虑使用purge_dups（https://github.com/dfguan/purge_dups）

**Comment by xiekunwhy** [comment]
不是期望Pandepth可以实现去冗余的功能，是要统计染色体间共享的reads数目（多重比对的reads可能会比对到多个染色体）。

**Comment by HuiyangYu** [comment]
如果是需要保留特定的flag并统计含有这些flag的reads的深度，比如'SUPPLEMENTARY', 实现的话可能简单一些。不过您这些需求的最终目的可能还是去除冗余，我们也在开发另外一款可以针对超大量基因组去冗余的工具，不需要进行reads的比对。

**Comment by xiekunwhy** [comment]
期待工具的发布，最好能把多个软件组装结果放到一起去冗余，选出连续性最好的Contig或者scaffold集合；还有一些物种必须多样本混装，比如蚂蚁这些小昆虫，所以最好也能考虑多样本混合组装的去冗余。

**Comment by HuiyangYu** [comment]
非常感谢您的建议。
