### ISSUE TITLE
distinguish with unaligned region and deletion region

### ISSUE THREAD

**Issue by baozg** [HuiyangYu/PanDepth#4]
Hi, @HuiyangYu 

Thanks for this super-fast tool. Is it possible to distinguish between the unaligned region (not in PAF) and deletion (D in the CIGAR) in the whole genome alignment?

**Comment by HuiyangYu** [comment]
Thank you very much for your appreciation of PanDepth. However, I regret to inform you that our tools may not directly meet your requirements. I am unsure whether you are looking for deletion type structural variants or have other specific needs. If it is the former, you may consider using tools such as Manta (short reads), cuteSV (long reads), paftools (genome), among others. For specialized requirements, you can temporarily utilize the ' -w ' parameter in PanDepth and set it to 50, 100, or other window size (bp). Regions with the coverage of 0 indicate unaligned region or deletion.

**Comment by baozg** [comment]
No, I don't want to call variants from PAF. But I am curious what's the exact meaning of coverage 0 in the PAF.  I think I could go back to the origanl PAF and use their coordinate as aligned region. If one deletion in the CIGAR, then `PanDepth` counts this region as 0, right?

**Comment by HuiyangYu** [comment]
The coverage of 0 indicates that this genomic region lacks any read/genome aligned, or that all reads/genome in this region are completely covered by a deletion.

**Comment by baozg** [comment]
Thank you for the clarification.
