### ISSUE TITLE
Is it possible to change an output dictionary?

### ISSUE THREAD

**Issue by HongyuanChu** [HuiyangYu/PanDepth#8]
Thanks for the software! My team is planning to cite PanDepth in a long-read sequencing pipeline for human. We really appreciate your work!
It would be better if we could change an output directionary rather than prefix only. This is meaningful especially when analysing many samples.

**Comment by HuiyangYu** [comment]
Thank you very much for your positive feedback on Pandepth. It is possible to specify a folder before the output file prefix. <br>For example: <br>```pandepth -i test.bam -o testDir/test```<br> The folder named 'testDir' must be pre-created
